user: 255
group: 245

permission:
  read: 107
  write: 179
  exec: 166
  exec-sticky: 203
  no-access: 240
  octal: 66
  acl: 66
  context: 66

date:
  hour-old: 114
  day-old: 179
  older: 245

size:
  none: 245
  small: 114
  medium: 179
  large: 209

inode:
  valid: 66
  invalid: 245

links:
  valid: 66
  invalid: 203

tree-edge: 240

git-status:
  default: 245
  unmodified: 245
  ignored: 240
  new-in-index: 107
  new-in-workdir: 107
  typechange: 179
  deleted: 203
  renamed: 66
  modified: 166
  conflicted: 203
